### ISSUE TITLE
Possible FSM Memory Leak

### ISSUE THREAD

**Issue by marumaru-games** [MinaPecheux/godot-tutorials#1]
Hi Mina, thanks for your C# tutorial on finite state machines (https://www.youtube.com/watch?v=Kcg1SEgDqyk). I'm using a similar FSM pattern in my own project, and I wanted to ask whether you have observed a potential memory leak via the object count when using a very basic FSM setup. When I create an empty idle state, I notice the object count in the debugger > monitors slowly climbing. Eventually, garbage collection occurs, but this can be after tens of thousands of objects have been created.

Here's a memory profile from your FSM demo

![Screenshot from 2023-09-27 10-43-53](https://github.com/MinaPecheux/godot-tutorials/assets/146146610/fa6e5ea7-370c-41ec-9483-f3e3873083f1)

Here it is in my project:

![memory_leak](https://github.com/MinaPecheux/godot-tutorials/assets/146146610/3b3aebee-b7ac-4ebb-8eff-9057c5594809)

Any idea what could be causing this?

**Steps to reproduce:**

1. Git clone your `godot-tutorials` repository
2. Run the FSM demo.tscn

**Environment:**

Godot v4.1.0
Dotnet SDK : 7.0.111

**Comment by marumaru-games** [comment]
Oh I think I managed to solve this!

![Screenshot from 2023-09-27 16-52-30](https://github.com/MinaPecheux/godot-tutorials/assets/146146610/822489a2-6150-445a-9562-47b46a30cf3c)

According to [this forum post,](https://ask.godotengine.org/154833/number-objects-grows-rapidly-input-activity-debug-monitor) we have to call `@event.Dispose();` or `using(@event){ ... }` within the input handler of the FSM:

```
    public override void _UnhandledInput(InputEvent @event)
    {
        _currentState.HandleInput(@event);
        @event.Dispose();
    }
```

Seems like a known memory leak: https://github.com/godotengine/godot/issues/41543

**Comment by MinaPecheux** [comment]
Hello,
and wow - many thanks for finding the bug AND solving it!! So cool :)

I'm indeed quite new to using the Input functions in Godot, so I definitely missed that - and didn't think to check memory leaks on a simple project like this one ^^

This is extremely cool - it gives me some ideas+extra material for an upcoming tutorials on handling inputs in Godot and monitoring your games.

Many thanks again - I've fixed the code according to your recommendation!
